#!/usr/bin/env node
/**
 * Generates an ambient TypeScript declaration file from the engine's real public
 * API, so the IDE's Monaco editor (and exported projects, for external editors)
 * get accurate autocomplete instead of hand-maintained, drifting types.
 *
 * How it works:
 *   1. Emit the engine's .d.ts via `tsc --emitDeclarationOnly`.
 *   2. Concatenate every declaration, stripping `import`/re-export statements and
 *      converting module declarations (`export declare function`) into ambient
 *      globals (`declare function`) — which is how event code uses the API.
 *   3. Neutralise the one external dependency (matter-js) to `any`.
 *   4. Write the result as a string constant the IDE feeds to Monaco.
 *
 * Run via `npm run gen:types` (also run automatically before build:ide).
 */

const fs   = require('node:fs')
const path = require('node:path')
const os   = require('node:os')
const { execFileSync } = require('node:child_process')

const ROOT       = path.resolve(__dirname, '..')
const ENGINE_TSC = path.join(ROOT, 'packages', 'engine', 'tsconfig.json')
const OUT_FILE   = path.join(ROOT, 'packages', 'ide', 'src', 'generated', 'engine_types.ts')

// 1. Emit engine declarations to a temp dir.
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'sw-dts-'))
try {
    execFileSync('npx', ['tsc', '-p', ENGINE_TSC, '--declaration', '--emitDeclarationOnly', '--outDir', tmp], {
        cwd: ROOT, stdio: 'inherit', shell: process.platform === 'win32',
    })

    // 2. Collect every emitted .d.ts.
    const files = []
    const walk = (dir) => {
        for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
            const p = path.join(dir, e.name)
            if (e.isDirectory()) walk(p)
            else if (e.name.endsWith('.d.ts')) files.push(p)
        }
    }
    walk(tmp)
    files.sort()

    // 3. Transform each file: drop imports/re-exports, ambient-ify declarations.
    const transform = (text) => text
        .replace(/^import .*$/gm, '')                                   // import statements
        .replace(/^export \* from '[^']*';?\s*$/gm, '')                 // export * from
        .replace(/^export type \{[^}]*\} from '[^']*';?\s*$/gm, '')     // export type {..} from
        .replace(/^export \{[^}]*\}(?: from '[^']*')?;?\s*$/gm, '')     // export {..} [from ..]
        .replace(/^export declare /gm, 'declare ')                      // export declare X -> declare X
        .replace(/^export interface /gm, 'interface ')
        .replace(/^export type /gm, 'type ')
        .replace(/^export abstract class /gm, 'abstract class ')

    let body = files.map(f => transform(fs.readFileSync(f, 'utf8'))).join('\n')

    // 4. Neutralise the one external dependency (matter-js) to `any`.
    body = body.replace(/\bMatter\.[A-Za-z_]\w*/g, 'any')

    // Collapse runs of blank lines for readability.
    body = body.replace(/\n{3,}/g, '\n\n').trim() + '\n'

    // 5. Write the string constant the IDE injects into Monaco.
    const header = `/**
 * AUTO-GENERATED by scripts/generate-types.cjs — do not edit by hand.
 * Ambient declarations of the Silkweaver engine's public API, derived from the
 * real engine source so IDE autocomplete cannot drift from the engine.
 */
/* eslint-disable */
export const ENGINE_DTS: string = ${JSON.stringify(body)}
`
    fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true })
    fs.writeFileSync(OUT_FILE, header, 'utf8')

    const fn_count = (body.match(/^declare function /gm) || []).length
    console.log(`[gen:types] wrote ${path.relative(ROOT, OUT_FILE)} (${body.length} chars, ${fn_count} functions)`)
} finally {
    fs.rmSync(tmp, { recursive: true, force: true })
}
